### PR TITLE
Added Dark mode toggle

### PR DESCRIPTION
**Pull request by therurouni**
Added dark mode for the entire page and added some UI effects too.Closes issue #16

### CODE REVIEW

**Comment by therurouni** [comment]
Hii @Yorichiiii22.Can u check this pr and merge it.(I'm participating in hacktoberfest so it would be helpful if u merge it faster)

**Comment by therurouni** [comment]
Hii @Yorichiiii22.Do u want me to add a button to it ?

**Comment by Yorichiiii22** [comment]
Yes @PAVAN507-STAR  to toggle between dark and light mode

**Comment by therurouni** [comment]
@Yorichiiii22  Okay so i should raise another pr right?

**Comment by Yorichiiii22** [comment]
@PAVAN507-STAR  yes you can!

**Pull request merged**
